### ISSUE TITLE
Argument chooses closing/opening etc. price for yf Ticker

### ISSUE THREAD

**Issue by wilhelmagren** [wilhelmagren/finq#20]
Add an argument to the fetch_data() function in Dataset to allow to save different time-of-day data.

OR we can just save all the types, and then let the user chose e.g. 'Closing' when retrieving it as a numpy array?..

**Comment by AugustSoderlund** [comment]
In fetch data, instead of `data[symbol] = pd.DataFrame(ticker.history(period=period)["Close"])`, we should retrieve OHLC in a dataframe. For example;

``` python
def fetch_data(...):
    ...
    for symbol in (bar := tqdm(self._symbols)):
        ticker = yf.Ticker(symbol, session=session)
        data[symbol] = pd.DataFrame(
                ticker.history(period=period)[
                    "Open",
                    "High",
                    "Low",
                    "Close",
                ]
            )
```

Then, in the `as_numpy()` function we can pass the argument for the desired series, such as:
```python
def as_numpy(
    self,
    series: Literal[
        "Open",
        "High",
        "Low",
        "Close",
    ] = "Close",
) -> np.ndarray:
    """ """
    return np.array([d[series] for d in self._data.values()]).astype(np.float32)
```

**Comment by wilhelmagren** [comment]
Looks like a really nice solution. Saving all data is definitely something we want to do :+1:

**Comment by wilhelmagren** [comment]
Might be tricky to rewrite this function https://github.com/wilhelmagren/finq/blob/f4b7fd036749db5fd0c3a683b6ac3a17eb1cb861/finq/datasets/dataset.py#L195 to allow for all prices?..

**Comment by AugustSoderlund** [comment]
> Might be tricky to rewrite this function
> 
> https://github.com/wilhelmagren/finq/blob/f4b7fd036749db5fd0c3a683b6ac3a17eb1cb861/finq/datasets/dataset.py#L195
> 
> to allow for all prices?..

@wilhelmagren I think it should be fine by doing 
```python
df = df.interpolate()
```
works by linearly interpolating missing values by using the surrounding values. It works for elements  in the beginning, middle and at the end.

**Comment by wilhelmagren** [comment]
Cool! I guess sometimes googling an extra time helps.. :P haha nice catch

**Comment by wilhelmagren** [comment]
The only caveat is that there are no NaN in the df to interpolate. the rows with the missing dates, are missing, so first we would have to add rows with index for the missing date, with value NaN, and then interpolate. I guess?

**Comment by AugustSoderlund** [comment]
Oh yeah, that's true. I'll try and see if I can loop over the OHLC instead 👍

**Comment by wilhelmagren** [comment]
Yea i think first we would have to loop over them, add the missing rows with NaN value, then call interpolate. :+1
