### ISSUE TITLE
Prepare PyPI release

### ISSUE THREAD

**Issue by wilhelmagren** [wilhelmagren/finq#26]
# Some open questions
## what name do we want on PyPI?
  - currently `finq` is already taken
  - we could do `py-finq` ? `pyfinq` ? `finqpy` ? something else?
  - please comment with suggestion

## Chores
- update pyproject.toml
  - authors,
  - version,
  - description,
  - etc ?..
- create setup.py (?)
- do we want CD workflow? deploy automatically to PyPI? might be a bit too much, we don't wanna do a lot of realeses?... thoughts?

**Comment by wilhelmagren** [comment]
Maybe try using [poetry](https://python-poetry.org/) , seems like a really nice tool

**Comment by wilhelmagren** [comment]
Preparing to publish using poetry. Most likely gonna use `pyfinq` as name on PyPI.Also rewriting both workflows to use poetry instead of pip.. gonna break main for a bit but its for the better good :shrug:

**Comment by AugustSoderlund** [comment]
> Preparing to publish using poetry. Most likely gonna use `pyfinq` as name on PyPI.Also rewriting both workflows to use poetry instead of pip.. gonna break main for a bit but its for the better good 🤷

Sounds good! 👍
